#!/usr/bin/env python3
##
## EPITECH PROJECT, 2026
## G2 - Shell PRogramming - 42sh
## File description:
## main file of the barcode built-in
##


from sys import stderr, stdout, argv, exit
import requests
from enum import Enum


API_URL = "https://barcode.tec-it.com/barcode.ashx"
DPI = 96
IMAGE_TYPE = "Png"
API_STATUS_SUCCESS = 200

EPITECH_SUCCESS = 0
EPITECH_FAILURE = 84

MIN_ARG_NBR = 3
MAX_ARG_NBR = 5
T_FLAG = "-t"
INDEX_T_FLAG = 1
INDEX_T_VAL = 2

DEFAULT_TYPE = "MobileQRCode"

BARCODE_TYPES = {
    "Code128" : (0,),
    "Code11" : (0,),
    "Code25IL" : (0,),
    "Code39" : (0,),
    "Code39FullASCII" : (0,),
    "Code93" : (0,),
    "Flattermarken" : (0,),
    "GS1-128" : (0,),
    "MSI" : (0,),
    "OneTrackPharmacode" : (0,),
    "TwoTrackPharmacode" : (0,),
    "TelepenAlpha" : (0,),
    "AustralianPost" : (1,),
    "DAFT" : (1,),
    "DPD" : (1,),
    "JapanesePostal" : (1,),
    "KIX" : (1,),
    "KoreanPostal" : (1,),
    "PlanetCode12" : (1,),
    "RoyalMail" : (1,),
    "RoyalMailMailmark" : (1,),
    "RoyalMailMailmark2d" : (1,),
    "PostNet5" : (1,),
    "PostNet9" : (1,),
    "PostNet11" : (1,),
    "USPSIMP" : (1,),
    "UPUS10" : (1,),
    "GS1DataBar" : (2,),
    "GS1DataBarStacked" : (2,),
    "GS1DataBarStackedOmni" : (2,),
    "GS1DataBarLimited" : (2,),
    "GS1DataBarExpanded" : (2,),
    "GS1DataBarExpandedStacked" : (2,),
    "GS1-128CCA" : (2,),
    "GS1DataBarCCA" : (2,),
    "GS1DataBarStackedCCA" : (2,),
    "GS1DataBarStackedOmniCCA" : (2,),
    "GS1DataBarLimitedCCA" : (2,),
    "GS1DataBarExpandedCCA" : (2,),
    "GS1DataBarExpandedStackedCCA" : (2,),
    "EAN8" : (3,),
    "EAN13" : (3,),
    "EAN14" : (3,),
    "EAN8CCA" : (3,),
    "EAN13CCA" : (3,),
    "UPCA" : (3,),
    "UPCE" : (3,),
    "UPCACCA" : (3,),
    "UPCECCA" : (3,),
    "QRCode" : (4,),
    "MobileQRCode" : (4,),
    "DataMatrix" : (4,),
    "Aztec" : (4,),
    "CodablockF" : (4,),
    "MaxiCode" : (4,),
    "MicroPDF417" : (4,),
    "PDF417" : (4,),
    "MicroQR" : (4,),
    "HanXin" : (4,),
    "DotCode" : (4,),
    "RoyalMail2D" : (4,),
    "NTIN" : (4,),
    "PPN" : (4,),
    "GS1QRCode" : (5,),
    "GS1DataMatrix" : (5,),
    "GS1DigitalLine_QRCode" : (5,),
    "GS1DigitalLine_DataMatrix" : (5,),
    "EPCQRCode" : (6,),
    "SwissQRCodeV23" : (6,),
    "SwissQRCodeV23SCOR" : (6,),
    "SwissQRCodeV23QRR" : (6,),
    "SwissQRCodeV2" : (6,),
    "SwissQRCodeV2SCOR" : (6,),
    "SwissQRCodeV2QRR" : (6,),
    "SwissQRCode" : (6,),
    "ZATCAQCode" : (6,),
    "MobileQRCode" : (7, 1),
    "MobileQRUrl" : (7, 1),
    "MobileQRPhone" : (7, 1),
    "MobileQRSMS" : (7, 1),
    "MobileQRTwitterProfile" : (7, 1),
    "MobileQRTwitterStatus" : (7, 1),
    "MobileQRFacebookProfile" : (7, 1),
    "MobileQRFacebookLike" : (7, 1),
    "MobileQRLinkedInProfile" : (7, 1),
    "MobileQRLinkedInCompanyProfile" : (7, 1),
    "MobileQRLinkedInShare" : (7, 1),
    "MobileQRAndroidMarketPubSearch" : (7, 1),
    "MobileQRAndroidMarketPackSearch" : (7, 1),
    "MobileSemaUrl" : (7, 2),
    "MobileSemaPhone" : (7, 2),
    "MobileSemaSMS" : (7, 2),
    "MobileSemaTwitterProfile" : (7, 2),
    "MobileSemaTwitterStatus" : (7, 2),
    "MobileSemaFacebookProfile" : (7, 2),
    "MobileSemaFacebookLike" : (7, 2),
    "MobileSemaLinkedInProfile" : (7, 2),
    "MobileSemaLinkedInCompanyProfile" : (7, 2),
    "MobileSemaLinkedInShare" : (7, 2),
    "MobileSemaAndroidMarketPubSearch" : (7, 2),
    "MobileSemaAndroidMarketPackSearch" : (7, 2),
    "MobileAztecUrl" : (7, 3),
    "MobileAztecPhone" : (7, 3),
    "MobileAztecSMS" : (7, 3),
    "MobileAztecTwitterProfile" : (7, 3),
    "MobileAztecTwitterStatus" : (7, 3),
    "MobileAztecFacebookProfile" : (7, 3),
    "MobileAztecFacebookLike" : (7, 3),
    "MobileAztecLinkedInProfile" : (7, 3),
    "MobileAztecLinkedInCompanyProfile" : (7, 3),
    "MobileAztecLinkedInShare" : (7, 3),
    "MobileAztecAndroidMarketPubSearch" : (7, 3),
    "MobileAztecAndroidMarcketPackSearch" : (7, 3),
    "Health_Code32" : (8,),
    "Health_Flattermarken" : (8,),
    "Health_HIBCLIC128" : (8,),
    "Health_HIBCLIC39" : (8,),
    "Health_HIBCLICAztec" : (8,),
    "Health_HIBCLICCodaF" : (8,),
    "Health_HIBCLICDataMatrix" : (8,),
    "Health_HIBCLICMicroPDF" : (8,),
    "Health_HIBCLICPDF417" : (8,),
    "Health_HIBCLICQR" : (8,),
    "Health_HIBCPAS128" : (8,),
    "Health_HIBCPAS39" : (8,),
    "Health_HIBCPASAztec" : (8,),
    "Health_HIBCPASCodaF" : (8,),
    "Health_HIBCPASDataMatrix" : (8,),
    "Health_HIBCPASMicroPDF" : (8,),
    "Health_HIBCPASPDF417" : (8,),
    "Health_HIBCPASQR" : (8,),
    "Health_NTIN" : (8,),
    "Health_Pharma1T" : (8,),
    "Health_Pharma2T" : (8,),
    "Health_PPN" : (8,),
    "Health_PZN7" : (8,),
    "Health_PZN8" : (8,),
    "ISBN13" : (9,),
    "ISBN13P5" : (9,),
    "ISMN" : (9,),
    "ISSN" : (9,),
    "ISSNP2" : (9,),
    "QRCode_Business_vCard" : (10,),
    "DataMatrix_Business_vCard" : (10,),
    "QRCode_Business_meCard" : (10,),
    "DataMatrix_Business_meCard" : (10,),
    "QRCode_Events" : (11,),
    "DataMatrix_Events" : (11,),
    "QRCode_Wifi" : (12,),
    "DataMatrix_Wifi" : (12,)
}
BARCODE_CATEGORIES = [
    "linear codes",
    "postal codes",
    "GS1 DataBar",
    "EAN / UPC",
    "2D Barcodes",
    "GS1 2D Barcodes",
    "electronic banking / SEPA",
    ("tagging mobile", ["QR codes", "data matrix", "aztec"]),
    "health_codes",
    "ISBN codes",
    "business cards",
    "calendar codes",
    "wi-fi barcodes"
]


def print_cat_content(cat:int, prefix:str="    ", output=stdout) -> None :
    for k in BARCODE_TYPES :
        if BARCODE_TYPES[k] == cat :
            print(f"{prefix}{k}", file=output)


def print_types(output=stdout) -> None :
    i = 0
    print("Barcode types :", file=output)
    for c in BARCODE_CATEGORIES :
        if type(c) == tuple :
            print(f"- {c[0]}", file=output)
            j = 0
            for sc in c[1] :
                print(f"    > {sc}", file=output)
                print_cat_content((i, j), prefix="        ", output=output)
                j += 1
        else :
            print(f"- {c}", file=stdout)
            print_cat_content((i,), prefix="    ", output=output)
        i += 1


def print_help(output=stdout) -> None :
    print("USAGE", file=output)
    print("    barcode [-t type] file data", file=output)
    print("", file=output)
    print("DESCRIPTION", file=output)
    print("    type    the barcode type ('QR Code Portable / Smartphone'" + \
        " by default)", file=output)
    print("    Create the barcode with the given data and save it into the " + \
        "file.", file=output)
    print("")
    print("run 'barcode -l' to see the barcode types list")


def create_barcode(content:str, barcode_type:str, path:str) -> int :
    if not(barcode_type in BARCODE_TYPES) :
        print(f"{barcode_type}: Invalid barcode type.\n", file=stderr)
        print_types(output=stderr)
        return EPITECH_FAILURE
    url = f"{API_URL}?data={content}&code={barcode_type}&dpi={DPI}&imagetype={ \
        IMAGE_TYPE}"
    response = requests.get(url)
    if response.status_code == API_STATUS_SUCCESS :
        file = open(path, "w+b")
        file.write(response.content)
        file.close()
        return EPITECH_SUCCESS
    print("barcode: API unable to create the barcode.", file=stderr)
    return EPITECH_FAILURE


if __name__ == "__main__" :
    if "-h" in argv :
        print_help()
        exit(EPITECH_SUCCESS)
    if "-l" in argv :
        print_types()
        exit(EPITECH_SUCCESS)
    if len(argv) < MIN_ARG_NBR :
        print("barcode: Missing arguments.\n", file=stderr)
        print_help(output=stderr)
        exit(EPITECH_FAILURE)
    if len(argv) > MAX_ARG_NBR :
        print("barcode: Too many arguments.\n", file=stderr)
        print_help(output=stderr)
        exit(EPITECH_FAILURE)
    type = DEFAULT_TYPE
    if argv[INDEX_T_FLAG] == T_FLAG :
        type = argv[INDEX_T_VAL]
        # argv = argv[INDEX_T_VAL + 1:]
        if len(argv) < MAX_ARG_NBR :
            print("barcode: Missing arguments after the '-t' option.\n", \
                file=stderr)
            print_help(output=stderr)
            exit(EPITECH_FAILURE)
    else :
        argv = argv[INDEX_T_FLAG:]
        if len(argv) > MIN_ARG_NBR :
            print("barcode: Too many arguments.\n", file=stderr)
            print_help(output=stderr)
            exit(EPITECH_FAILURE)
    # if len(argv) < MIN_ARG_NBR :
    #     print("barcode: Missing arguments after the '-t' option.\n", \
    #         file=stderr)
    #     print_help(output=stderr)
    #     exit(EPITECH_FAILURE)
    file, data = argv[0], argv[1]
    exit(create_barcode(data, type, file))
